"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TransactionType = exports.ThirdParty = exports.Pending = exports.LenderType = exports.CreditDebit = exports.Description = exports.CategoryEnum = exports.AnalysisPointType = exports.Title = exports.AnalysisPointName = void 0;
var AnalysisPointName;
(function (AnalysisPointName) {
    AnalysisPointName["AmountFunded"] = "amountFunded";
    AnalysisPointName["AmountReversals"] = "amountReversals";
    AnalysisPointName["AverageAmountFunded"] = "averageAmountFunded";
    AnalysisPointName["AverageDebitAmount"] = "averageDebitAmount";
    AnalysisPointName["AverageTransactionAmount"] = "averageTransactionAmount";
    AnalysisPointName["CountOfDebits"] = "countOfDebits";
    AnalysisPointName["CountOfLoans"] = "countOfLoans";
    AnalysisPointName["CountOfLoansFunded"] = "countOfLoansFunded";
    AnalysisPointName["CountOfOngoingLoans"] = "countOfOngoingLoans";
    AnalysisPointName["CountOfProviders"] = "countOfProviders";
    AnalysisPointName["CountOfTransactions"] = "countOfTransactions";
    AnalysisPointName["CountReversals"] = "countReversals";
    AnalysisPointName["DaysSinceLastTransaction"] = "daysSinceLastTransaction";
    AnalysisPointName["EndDate"] = "endDate";
    AnalysisPointName["Frequency"] = "frequency";
    AnalysisPointName["FrequencyDay"] = "frequencyDay";
    AnalysisPointName["LoanOngoing"] = "loanOngoing";
    AnalysisPointName["MonthlyAmountAverage"] = "monthlyAmountAverage";
    AnalysisPointName["OngoingRepaymentAmount"] = "ongoingRepaymentAmount";
    AnalysisPointName["StartDate"] = "startDate";
    AnalysisPointName["TotalAmount"] = "totalAmount";
    AnalysisPointName["TotalAmountCredits"] = "totalAmountCredits";
    AnalysisPointName["TotalAmountDebits"] = "totalAmountDebits";
    AnalysisPointName["TotalAmountLast30Days"] = "totalAmountLast30Days";
})(AnalysisPointName = exports.AnalysisPointName || (exports.AnalysisPointName = {}));
var Title;
(function (Title) {
    Title["AmountDebits"] = "Amount Debits";
    Title["AmountFunded"] = "Amount Funded";
    Title["AmountOfReversals"] = "Amount of Reversals";
    Title["AverageAmountFunded"] = "Average Amount Funded";
    Title["AverageDebitAmount"] = "Average Debit Amount";
    Title["AverageTransactionAmount"] = "Average Transaction Amount";
    Title["CountOfDebits"] = "Count of Debits";
    Title["CountOfLoans"] = "Count of Loans";
    Title["CountOfLoansFunded"] = "Count of Loans Funded";
    Title["CountOfOngoingLoans"] = "Count of Ongoing Loans";
    Title["CountOfProviders"] = "Count of Providers";
    Title["CountOfReversals"] = "Count of Reversals";
    Title["CountOfTransactions"] = "Count of Transactions";
    Title["DaysSinceLastTransaction"] = "Days Since Last Transaction";
    Title["EndDate"] = "End Date";
    Title["Frequency"] = "Frequency";
    Title["FrequencyDay"] = "Frequency Day";
    Title["LoanOngoing"] = "Loan Ongoing";
    Title["MonthlyAverageAmount"] = "Monthly Average Amount";
    Title["OngoingRepaymentAmount"] = "Ongoing Repayment Amount";
    Title["StartDate"] = "Start Date";
    Title["TotalAmount"] = "Total Amount";
    Title["TotalAmountCredits"] = "Total Amount - Credits";
    Title["TotalAmountDebits"] = "Total Amount - Debits";
    Title["TotalAmountLast30Days"] = "Total Amount - Last 30 Days";
})(Title = exports.Title || (exports.Title = {}));
var AnalysisPointType;
(function (AnalysisPointType) {
    AnalysisPointType["Date"] = "date";
    AnalysisPointType["Integer"] = "integer";
    AnalysisPointType["Money"] = "money";
    AnalysisPointType["String"] = "string";
})(AnalysisPointType = exports.AnalysisPointType || (exports.AnalysisPointType = {}));
var CategoryEnum;
(function (CategoryEnum) {
    CategoryEnum["AllOtherCredits"] = "All Other Credits";
    CategoryEnum["Centrelink"] = "Centrelink";
    CategoryEnum["ExternalTransfers"] = "External Transfers";
    CategoryEnum["Fees"] = "Fees";
    CategoryEnum["Gambling"] = "Gambling";
    CategoryEnum["Groceries"] = "Groceries";
    CategoryEnum["InternalTransfer"] = "Internal Transfer";
    CategoryEnum["NonSACCLoans"] = "Non SACC Loans";
    CategoryEnum["Overdrawn"] = "Overdrawn";
    CategoryEnum["RefundsAndReturns"] = "Refunds and Returns";
    CategoryEnum["Rent"] = "Rent";
    CategoryEnum["SACCLoans"] = "SACC Loans";
    CategoryEnum["Telecommunications"] = "Telecommunications";
    CategoryEnum["UncategorisedDebits"] = "Uncategorised Debits";
    CategoryEnum["Wages"] = "Wages";
})(CategoryEnum = exports.CategoryEnum || (exports.CategoryEnum = {}));
var Description;
(function (Description) {
    Description["AnUncategorisedDebit"] = "An uncategorised debit";
    Description["AutomaticDrawingO13439G2GLoansGoodToGoLoans"] = "AUTOMATIC DRAWING O13439 G2G LOANS GOOD TO GO LOANS";
    Description["BPAYMoneyToTelstra"] = "BPAY Money to Telstra";
    Description["CtrlinkNewstart"] = "Ctrlink Newstart";
    Description["DebitExcessInterest"] = "Debit Excess Interest";
    Description["DirectDebit428198FERRATUM11813938"] = "Direct Debit 428198 FERRATUM 11813938";
    Description["DirectDebit843752GymMembership"] = "Direct Debit 843752 Gym Membership";
    Description["DirectRVSL301500FerratumAustralLoan419913"] = "Direct RVSL 301500 Ferratum Austral Loan 419913";
    Description["DirectRVSLToCompany"] = "Direct RVSL to company";
    Description["EftposWoolworths1111BentleyWaAu"] = "EFTPOS WOOLWORTHS 1111BENTLEY WA AU";
    Description["InterestCurrentRateIs105"] = "Interest - current rate is 1.05%";
    Description["LoanPayment"] = "Loan payment";
    Description["LoanRepayment"] = "Loan Repayment";
    Description["MaintenanceFee"] = "Maintenance Fee";
    Description["Misc"] = "Misc";
    Description["MoneyFromCrownbet"] = "Money from Crownbet";
    Description["MoneyMeLoanFunded"] = "MoneyMe Loan Funded";
    Description["MoneyMePayment"] = "MoneyMe payment";
    Description["MoneyToCrownbet"] = "Money to Crownbet";
    Description["PendingTransaction"] = "Pending Transaction";
    Description["RentPayment"] = "Rent payment";
    Description["SunshineLoanRepayment"] = "Sunshine Loan Repayment";
    Description["TransactionDetailsAvailableNextBusinessDay"] = "Transaction Details Available Next Business Day";
    Description["VisaPendingEFTPOSWOOLWORTHS1111DATETESTWAAU"] = "Visa Pending: EFTPOS WOOLWORTHS 1111DATETEST WA AU";
    Description["WageFromDeliveryServiceJob"] = "Wage from delivery service job";
})(Description = exports.Description || (exports.Description = {}));
var CreditDebit;
(function (CreditDebit) {
    CreditDebit["Credit"] = "credit";
    CreditDebit["Debit"] = "debit";
})(CreditDebit = exports.CreditDebit || (exports.CreditDebit = {}));
var LenderType;
(function (LenderType) {
    LenderType["OtherLoansOnly"] = "Other loans only";
    LenderType["SACCLoansOnly"] = "SACC loans only";
    LenderType["SACCSAndOtherLoans"] = "SACCs and Other loans";
})(LenderType = exports.LenderType || (exports.LenderType = {}));
var Pending;
(function (Pending) {
    Pending["Pending"] = "pending";
})(Pending = exports.Pending || (exports.Pending = {}));
var ThirdParty;
(function (ThirdParty) {
    ThirdParty["BetEasy"] = "BetEasy";
    ThirdParty["DirectDebit"] = "Direct Debit";
    ThirdParty["Ferratum"] = "Ferratum";
    ThirdParty["GoodToGo"] = "Good To Go";
    ThirdParty["JobSeeker"] = "JobSeeker";
    ThirdParty["LoanRepaymentDebit"] = "Loan Repayment Debit";
    ThirdParty["MoneyMe"] = "MoneyMe";
    ThirdParty["OtherCredits"] = "Other Credits";
    ThirdParty["OtherTransfers"] = "Other Transfers";
    ThirdParty["PendingTransfer"] = "Pending Transfer";
    ThirdParty["Rent"] = "Rent";
    ThirdParty["SunshineLoans"] = "Sunshine Loans";
    ThirdParty["Telstra"] = "Telstra";
    ThirdParty["Wages"] = "Wages";
    ThirdParty["Woolworths"] = "Woolworths";
})(ThirdParty = exports.ThirdParty || (exports.ThirdParty = {}));
var TransactionType;
(function (TransactionType) {
    TransactionType["DirectDebit"] = "Direct Debit";
    TransactionType["Empty"] = "";
    TransactionType["GeneralPayment"] = "General Payment";
    TransactionType["InboundTransfer"] = "Inbound Transfer";
    TransactionType["Informational"] = "Informational";
    TransactionType["MaintenanceFees"] = "Maintenance Fees";
    TransactionType["OverdrawnFees"] = "Overdrawn Fees";
    TransactionType["ReversedTransactions"] = "Reversed Transactions";
    TransactionType["WelfarePayments"] = "Welfare Payments";
})(TransactionType = exports.TransactionType || (exports.TransactionType = {}));
